Senegal2018 revise
wengxyu1030/DHS-Recode-VII pull request #14
Opened 2021-05-13 17:59 UTC by yining-sun

- updated codes in 1.do- ANC
- updated codes in 2.do- delivery care - updated 11.do- sleeping under bednet. Count both treated and nontreated as ITN. Recode mother education = 6 as missing.
- Changed codes in 7.do child vaccination to ensure kids 15-23 months old receiving measles2 are coded as measles1.
- Revised comments on Child Illness.

2021-05-14 11:02 UTC, wengxyu1030 requested changes
@yining-sun Thanks for the modifications, they look good. But I have put my comments where improvement could be made.

2021-05-14 11:02 UTC, wengxyu1030 commented on 1_antenatal_care.do
> +	if inlist(name, "Senegal2018") {
I would suggest to put the surveys in similar condition together to simply the command, for this, `if inlist(name,"Senegal2018", "Senegal2019", "Senegal2017")` would be better, could you modify？

2021-05-14 11:02 UTC, wengxyu1030 commented on 2_delivery_care.do
> +
Could you follow my same suggestion that collapse the condition for surveys as below?
```suggestion
	 if inlist(name,"Senegal2018", "Senegal2019", "Senegal2017")

```

2021-05-14 11:02 UTC, wengxyu1030 commented on 7_child_vaccination.do
> +		if inlist(name, "Senegal2018") {
Please collapse the conditions as I suggested in the previous comments.

2021-05-17 00:10 UTC, yining-sun commented on 1_antenatal_care.do
> +	if inlist(name, "Senegal2018") {
@wengxyu1030 Dear Aline, I have updated the codes accordingly. Thanks for the comments!

2021-05-17 08:33 UTC, merged

2021-05-17 08:33 UTC, wengxyu1030 commented
Well done @yining-sun, I have reviewed your changes and it's good to go. I thereby merging it to the master file.